### ISSUE TITLE
Publish new release (with Django 2.0 support)

### ISSUE THREAD

**Issue by jdufresne** [twidi/django-decorator-include#52]
Hi @twidi 

Thanks for maintaining django-decorator-include and merging the Django 2.0 support. What are you thoughts on publishing a new release so it can be integrated into projects?

Do you think #51 should be merged before or after? I'm happy with either. Thanks!

**Comment by twidi** [comment]
Tomorrow I'll rework the setup (to go full setup.cfg, as I learn while doing my talk on the subject last year (french only, sorry)), then we'll be ok for a go!

**Comment by twidi** [comment]
I would like to do two releases. 1.4 with the current state, then a 2.0, removing support for python 2, both today.

**Comment by twidi** [comment]
First step ready in #56.

When reviewed and if approved, I'll create a release branch for 1.4.

I'll now work on the 2.0 version for python 3 only.

**Comment by twidi** [comment]
#57 is merged and 1.4 published on pypi. Still work in progress for 2.0. Wanted to try something that failed miserably ;)

**Comment by twidi** [comment]
#58 is ready!

**Comment by twidi** [comment]
So it's done. Version 1.4 for Django 1.11 & 2.0, Python 2.7 and 3.4+
And version 2.0 for Django 2.0 and Python 3.4+ only
