### ISSUE TITLE
not a registered namespace exception when using django-decorator-include

### ISSUE THREAD

**Issue by deasek** [twidi/django-decorator-include#66]
I use `django 2.0.7` in my project with `django-decorator-include` app (version 2.0).

My urls.py:

    from django.conf import settings
    from django.contrib import admin
    from django.urls import path, re_path, include
    from django.conf.urls.static import static
    
    from django.conf.urls.i18n import i18n_patterns
    from django.contrib.auth.decorators import login_required
    from decorator_include import decorator_include
    
    
    urlpatterns = i18n_patterns(
        path('', include('web.urls', namespace='web')),
        path('backoffice/', decorator_include([login_required,], 'backoffice.urls', namespace='backoffice')),
    
    ) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

My `backoffice.urls`:

    from django.urls import path, re_path
    from django.conf.urls.i18n import i18n_patterns
    from django.utils.translation import gettext_lazy as _
    
    from backoffice import views
    
    app_name = 'backoffice'
    
    urlpatterns = (
        path('', views.DashboardView.as_view(), name='dashboard'),
    )

`backoffice` is added to **INSTALLED_APPS**.

In my views (in app `web` for example) I am able to do reverse URL, for example in my login view I do `return redirect('backoffice:dashboard')` and it works just perfectly - its redirecting to /backoffice/.

Problem is when I try to do reverse urls in my templates. In one of my templates, when I add code:

    <li class="featured"><a href="{% url 'backoffice:dashboard' %}">{% trans 'Open dashboard' %}</a></li>

I get django error:

    NoReverseMatch at /
    'backoffice' is not a registered namespace

I suppose that problem is related to django-decorator-include, because if I change my include to standard django url include:

    path('backoffice/', include('backoffice.urls', namespace='backoffice')),

it works just fine, and I am able to get reverse urls in templates again.
Has anyone observed similar behaviour?

**Comment by robsimpsondev** [comment]
I've got this behaviour. Exactly the same, but from the default django auth login form.

If I add login_required line-by-line inside the app I have no problem, so I think it is to do with decorator_include.

For reference my `$ ./manage.py show_urls` shows the namespaced URLs I need.

Did you find a solution?

**Comment by MohsenHassani** [comment]
I've been struggling with this problem for like one month now.
I never had a problem with Django < 2.0
I haven't found any solutions yet, I hope @twidi manages to solve it soon.
I already appreciate @twidi  for such a cool package.

**Comment by deasek** [comment]
@MohsenHassani @robsimpsondev 
Guys,
here is my workaround (worked in my case) - just change the way how you define include.

```
from backoffice.urls import urlpatterns as backoffice_urlpatterns

urlpatterns = i18n_patterns(
    path('admin/', admin.site.urls),
    path('backoffice/', decorator_include([login_required, ], (backoffice_urlpatterns, 'backoffice'))),
) 
```

**Comment by MohsenHassani** [comment]
Thank you so much @deasek  for sharing your solution! 
It worked just like a charm!
And here's how I got it working as you said:
`
urlpatterns = [
    path('admin/', decorator_include([staff_required], ('staff.urls', 'staff'))),
]
`
and well there was no need to put `app_name = 'staff'` in staff.urls, which existence is a new rule of Django 2.0, I don't know why it works without that.

**Comment by jdufresne** [comment]
Thanks for identifying the bug. To anyone able, a fix that includes a test would be very welcome.

**Comment by twidi** [comment]
Version 3.0 to come soon will behave with namespace/app_name like the django `include` function. See #78

**Comment by twidi** [comment]
version 3.0 is now on pypi
