### ISSUE TITLE
support decorators that use parameters

### ISSUE THREAD

**Issue by hosler** [twidi/django-decorator-include#77]
required permissions decorator takes in arguments. maybe pass them in as a tuple and use something like this?
```           
     for decorator in reversed(self.decorators):
                if isinstance(decorator, tuple):
                    callback = decorator[0](decorator[1])(callback)
                else:
                    callback = decorator(callback)
```

**Comment by twidi** [comment]
Version 3.0 to come soon has a test to ensure that parameterized decorators (including the `permission_required` from django) work as expected. See #80

**Comment by twidi** [comment]
version 3.0 is now on pypi
