### ISSUE TITLE
Support for django 3.2?

### ISSUE THREAD

**Issue by SiddChugh** [twidi/django-decorator-include#88]
Can the maintainers verify that this package is indeed supported for [django 3.2](https://github.com/django/django/tree/3.2.7)?

**Comment by DmytroLitvinov** [comment]
Hi @twidi ,
I am ready to provide related PR for that.

**Comment by StevenMapes** [comment]
It is as I am using it on 3.2 and have been for some time

**Comment by SiddChugh** [comment]
thanks @StevenMapes . I just wish maintainers took some ownership. 
Closing the issue...

**Comment by StevenMapes** [comment]
I've updated my PR to include tests for Django 4.0 and Django 4.1 support
