### ISSUE TITLE
Upgrade to Django 4.2 breaks with TypeError: 'module' object is not iterable

### ISSUE THREAD

**Issue by gabn88** [twidi/django-decorator-include#97]
I installed the developer branch from @StevenMapes, but still it is not working on Django4.2 for me, while it was working fine before.

Example code:

```
    path('', decorator_include(login_required, index_url)),
```

Error stacktrace:

```
  File "/python3.9/site-packages/decorator_include.py", line 67, in urlpatterns
    return [self.decorate_pattern(pattern) for pattern in patterns]
TypeError: 'module' object is not iterable
```

**Comment by gabn88** [comment]
Oh my. I did a replace all to replace url by re_path, but urlpatterns was replaced by re_pathpatterns in urls.py. Of course that didn't work. Sorry to bother.

**Comment by StevenMapes** [comment]
Version 3.1 is now out with my fork merged in so please switch back to using the main pypi one as I'll be maintaining this repository moving forward
